### PR TITLE
qbt hash torrent/magnet to print hash

### PR DESCRIPTION
**Pull request by klahaha**
i dont think support bittorrentv2 magnet/torrent (not tested)

always print newline after hash (not detect interactive terminal) can be improved but want your reaction first

### CODE REVIEW

**Comment by klahaha** [comment]
context: i add torrent to /torrent/%HASH% i need hash for this. i run with #28 also (for now my script use qbc i have not replaced all with qbt but i want to)

**Review by ludviglundgren — APPROVED** [review]
Hello, thanks for the PR. This is not something I will use myself, but if it's useful to you then thats enough :slightly_smiling_face: 

And yes you are probably correct about v2 torrents. The underlying library will have to update and support that.

**Comment by klahaha** [comment]
> if it's useful to you then thats enough slightly_smiling_face

thanks

improvement for detect interactive terminal. demo:

```
klahaha@k$ bin/qbt hash "magnet:?xt=urn:btih:e368633c136582fc3eab4a77b1c75c36151a8eef&dn=archlinux-2022.01.01-x86_64.iso"
e368633c136582fc3eab4a77b1c75c36151a8eef
klahaha@k$ res="$(bin/qbt hash "magnet:?xt=urn:btih:e368633c136582fc3eab4a77b1c75c36151a8eef&dn=archlinux-2022.01.01-x86_64.iso")"; echo "-$res-"
-e368633c136582fc3eab4a77b1c75c36151a8eef-
klahaha@k$ 
```

with this you can use in script and not have newline from your script but i dont understand in docs [os.LookupEnv](https://pkg.go.dev/os#LookupEnv) says return false when variable not found but i think it does opposite (i must do if !found print new line)? go1.17.6 here can you try too?

**Comment by ludviglundgren** [comment]
Ok, then I'll merge this 👍

**Pull request merged**
